---
name: Release 🚀

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_call:
    secrets:
      REPO_GITHUB_TOKEN:
        description: |
          Github token with write access to the repository
        required: false
    inputs:
      create-rc-releases:
        description: Whether releases for RC tags (e.g. v0.0.1-rc1) should be created?
        required: false
        default: false
        type: boolean
      package-subdirectory:
        description: Subdirectory in the repository, where the R package is located.
        required: false
        type: string
        default: "."
  workflow_dispatch:

concurrency:
  group: release-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release 🚀
    runs-on: ubuntu-latest
    if: "! contains(github.event.commits[0].message, '[skip release]')"
    permissions:
      contents: write
    container:
      image: ghcr.io/insightsengineering/rstudio_4.3.1_bioc_3.17:latest
    steps:
      - name: Setup token 🔑
        id: github-token
        run: |
          if [ "${{ secrets.REPO_GITHUB_TOKEN }}" == "" ]; then
            echo "REPO_GITHUB_TOKEN is empty. Substituting it with GITHUB_TOKEN."
            echo "token=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          else
            echo "Using REPO_GITHUB_TOKEN."
            echo "token=${{ secrets.REPO_GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Checkout repo 🛎
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch names 🌿
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Check if running for rc tag 🏷️
        id: rc-tag
        run: |
          echo "Current tag: ${{ steps.branch-name.outputs.tag }}"
          current_tag="${{ steps.branch-name.outputs.tag }}"
          if [ "$(echo "$current_tag" | grep -E "^v([0-9]+\.)?([0-9]+\.)?([0-9]+)(-rc[0-9]+)$")" != "" ]; then
            echo "Running for rc-tag."
            echo "is-rc-tag=true" >> $GITHUB_OUTPUT
          else
            echo "is-rc-tag=false" >> $GITHUB_OUTPUT
          fi
          git config --global --add safe.directory $(pwd)
          git checkout main || true
          git fetch origin main || true
          git pull origin main || true
          git remote -v
        shell: bash

      - name: Generate Changelog 📜
        if: >-
          steps.rc-tag.outputs.is-rc-tag == 'false' ||
            inputs.create-rc-releases == true
        run: |
          Sys.setenv(GITHUB_PAT_GITHUB_COM = "${{ steps.github-token.outputs.token }}")
          Sys.setenv(GITHUB_PAT = "${{ steps.github-token.outputs.token }}")
          usethis::use_github_release(publish = TRUE)
        working-directory: ${{ inputs.package-subdirectory }}
        shell: Rscript {0}

      # - name: Create release 🌟
      #   if: >-
      #     steps.rc-tag.outputs.is-rc-tag == 'false' ||
      #       inputs.create-rc-releases == true
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     body_path: ${{ inputs.package-subdirectory }}/RELEASE_BODY.txt
      #     token: ${{ steps.github-token.outputs.token }}
      #     generate_release_notes: true
